// Player portraits, keyed by the short name used in each era's XI.
//
// Each player is resolved through Wikidata rather than an image search: the
// entity must be a human (P31=Q5) whose occupation is footballer or manager
// (P106), and we take that entity's canonical image (P18). That matters —
// a plain Commons text search returned the wrong people entirely (a USA
// women's international for "Lauren", the 1960s Spaniard for "Suárez", and
// Fredy Guarín for "Maicon"), because it matches filenames, not identities.
//
// Every image is CC0/CC BY/CC BY-SA, all of which require visible credit, so
// the inspector renders the photographer, licence and source link beside the
// portrait — do not remove that. Players absent from this map (no free image
// on Wikidata) fall back to the shield placeholder.

export type PlayerPhoto = {
  file: string;
  author: string;
  licence: string;
  licenceUrl: string;
  source: string;
};

export const PLAYER_PHOTOS: Record<string, PlayerPhoto> = {
  'A. Cole': {
    file: 'a-cole.jpg',
    author: 'Stanislav Vedmid',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:ACole.JPG',
  },
  'Abidal': {
    file: 'abidal.jpg',
    author: 'Mutari 16:30, 5 March 2008 (UTC)',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:%C3%89ric_Abidal_-_001.jpg',
  },
  'Agüero': {
    file: 'aguero.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ag%C3%BCero_in_2018.jpg',
  },
  'Alaba': {
    file: 'alaba.jpg',
    author: 'Granada',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:20180610_FIFA_Friendly_Match_Austria_vs._Brazil_David_Alaba_850_1632.jpg',
  },
  'Alba': {
    file: 'alba.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Russia-Spain_2017_(11).jpg',
  },
  'Alex': {
    file: 'alex.jpg',
    author: 'TomekBlaszczyk',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Alex_Rodrigo_Dias_da_Costa.jpg',
  },
  'Alexander-Arnold': {
    file: 'alexander-arnold.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Trent_Alexander-Arnold_2018_(cropped).jpg',
  },
  'Alisson': {
    file: 'alisson.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Alisson_Becker_Brazil_V_Morocco_13_June_2026-117_(cropped).jpg',
  },
  'Alves': {
    file: 'alves.jpg',
    author: 'Palácio do Planalto from Brasilia, Brasil',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:07_07_2019_Final_da_Copa_Am%C3%A9rica_2019_(48226649586)_(cropped).jpg',
  },
  'Ambrosini': {
    file: 'ambrosini.jpg',
    author: 'Io',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Massimo_Ambrosini_in_2008.jpg',
  },
  'Amor': {
    file: 'amor.jpg',
    author: 'Jordiferrer',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Guillermo-Amor-Barcelona-1992.jpg',
  },
  'Bakero': {
    file: 'bakero.jpg',
    author: 'Roger Goraczniak',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jos%C3%A9_Mari_Bakero.jpg',
  },
  'Bale': {
    file: 'bale.jpg',
    author: 'Дмитрий Журавель',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gareth_Bale_2015_(1).jpg',
  },
  'Ballack': {
    file: 'ballack.jpg',
    author: 'Bernhard Holub',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Michael_Ballack_2022_BHO-0832.jpg',
  },
  'Beckham': {
    file: 'beckham.jpg',
    author: 'The Democratic Alliance',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:David_Beckham_2009.jpg',
  },
  'Beguiristain': {
    file: 'beguiristain.jpg',
    author: 'Biser Todorov',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Txiki_Begiristain_2016_(cropped).jpg',
  },
  'Benzema': {
    file: 'benzema.jpg',
    author: 'Zack',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Karim_Benzema_Pick.jpg',
  },
  'Bergkamp': {
    file: 'bergkamp.jpg',
    author: 'Kieran Clarke',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dennis_Bergkamp_2014_(cropped).jpg',
  },
  'Boateng': {
    file: 'boateng.jpg',
    author: 'Rufus46',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jerome_Boateng_Training_2019-04-10_FC_Bayern_Muenchen-2_(cropped).jpg',
  },
  'Brown': {
    file: 'brown.jpg',
    author: 'Andrea Sartorati',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Brown_Manchester_-_Old_Trafford_-_Manchester_United_vs_Crawley_Town.jpg',
  },
  'Busquets': {
    file: 'busquets.jpg',
    author: 'Анна Нэсси',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sergio_Busquets_2018_(cropped).jpg',
  },
  'C. Alberto': {
    file: 'c-alberto.jpg',
    author: 'Shaoqiang at German Wikipedia jugo junto al colombiano camilo arce leon (Original text: \'camilo arce)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Calberto.jpg',
  },
  'Cambiasso': {
    file: 'cambiasso.jpg',
    author: 'Ludovic Péron',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Esteban_Cambiasso_-_2011.jpg',
  },
  'Campbell': {
    file: 'campbell.jpg',
    author: 'Stefan Schäfer, Lich',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sol_Campbell2014.jpg',
  },
  'Carrick': {
    file: 'carrick.jpg',
    author: 'Timmy96',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Michael_Carrick_12042025_(5)_(cropped).jpg',
  },
  'Carvajal': {
    file: 'carvajal.jpg',
    author: 'Rolandhino1',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Dani_Carvajal_10_(cropped).jpg',
  },
  'Carvalho': {
    file: 'carvalho.jpg',
    author: 'Jan S0L0',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Carvalho_in_2010-11_Real_Madrid.jpg',
  },
  'Casemiro': {
    file: 'casemiro.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Casemiro_Brazil_V_Morocco_13_June_2026-76_(cropped).jpg',
  },
  'Casillas': {
    file: 'casillas.jpg',
    author: 'Зайцев Антон',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Iker_Casillas_2.jpg',
  },
  'Čech': {
    file: 'cech.jpg',
    author: 'Warrenfish',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Petr_%C4%8Cech_Chelsea_2013.jpg',
  },
  'Chivu': {
    file: 'chivu.jpg',
    author: 'Майоров Владимир',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cristian_Chivu_2011.jpg',
  },
  'Cleverley': {
    file: 'cleverley.jpg',
    author: 'Tommy Low from Singapore, Singapore',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tom_Cleverley_2015.jpg',
  },
  'Coentrão': {
    file: 'coentrao.jpg',
    author: 'Майоров Владимир',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:4F%C3%A1bio_Coentr%C3%A3o.jpg',
  },
  'Cole': {
    file: 'cole.jpg',
    author: 'Norio NAKAYAMA from saitama, japan',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Aeroflot_Manchester_United_Trophy_Tour_in_Tokyo_(13047502155).jpg',
  },
  'Costinha': {
    file: 'costinha.jpg',
    author: 'Christophe95',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Costinha_(footballer_born_1974).jpg',
  },
  'D. Silva': {
    file: 'd-silva.jpg',
    author: 'Дмитрий Неймырок',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:David_Silva_Euro_2012_vs_France_01.jpg',
  },
  'De Bruyne': {
    file: 'de-bruyne.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_(cropped).jpg',
  },
  'De Gea': {
    file: 'de-gea.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:David_de_Gea_2017.jpg',
  },
  'Deco': {
    file: 'deco.jpg',
    author: 'John Dobson',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Chelsea_Deco.jpg',
  },
  'Delph': {
    file: 'delph.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fabian_Delph_2018-06-28_3.jpg',
  },
  'Dembélé': {
    file: 'dembele.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ousmane_Dembele_France_v_Senegal_16_June_2026-341_(cropped).jpg',
  },
  'Derlei': {
    file: 'derlei.jpg',
    author: 'Alexander Oganezov aka Sasho68',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Derlei.jpg',
  },
  'Di María': {
    file: 'di-maria.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:NIG-ARG_(5).jpg',
  },
  'Dida': {
    file: 'dida.jpg',
    author: 'NullReason',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dida-wikipedia_(cropped_2).png',
  },
  'Donnarumma': {
    file: 'donnarumma.jpg',
    author: 'Original: MichaelEmilio / Derivative work: Danyele',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Norway_Italy_-_June_2025_B_33_-_Gianluigi_Donnarumma_(close-up).jpg',
  },
  'Doué': {
    file: 'doue.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Desire_Doue_France_v_Norway_26_June_26-032.jpg',
  },
  'Drogba': {
    file: 'drogba.jpg',
    author: 'Y.Leclercq©',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Didier_Drogba_(2019)_(cropped).jpg',
  },
  'Duff': {
    file: 'duff.jpg',
    author: 'Mikhail Slain',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:DDuff.JPG',
  },
  'Ederson': {
    file: 'ederson.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ederson_(cropped).png',
  },
  'Eto\'o': {
    file: 'eto-o.jpg',
    author: 'BACHELOR45',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sammuel_Eto%27o_Fils_02.jpg',
  },
  'Evra': {
    file: 'evra.jpg',
    author: 'Web Summit',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Patrice_Evra_(52472689279)_(cropped).jpg',
  },
  'Fabinho': {
    file: 'fabinho.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fabinho_Brazil_V_Morocco_13_June_2026-70.jpg',
  },
  'Ferdinand': {
    file: 'ferdinand.jpg',
    author: 'Web Summit',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Web_Summit_2015_-_Dublin,_Ireland_-_22183056474_(cropped).jpg',
  },
  'Fernandinho': {
    file: 'fernandinho.jpg',
    author: 'Ailura',
    licence: 'CC BY-SA 3.0 at',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/at/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:20141118_AUTBRA_5080.jpg',
  },
  'Ferrer': {
    file: 'ferrer.jpg',
    author: 'Jordiferrer',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Albert-Ferrer-Barcelona-1992.jpg',
  },
  'Firmino': {
    file: 'firmino.jpg',
    author: 'Granada',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Roberto_Firmino_850_1557.jpg',
  },
  'G. Neville': {
    file: 'g-neville.jpg',
    author: 'University of Salford Press Office',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gary_Neville_2014_(cropped).jpg',
  },
  'Gallas': {
    file: 'gallas.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:William_Gallas_2018_(2).jpg',
  },
  'Gattuso': {
    file: 'gattuso.jpg',
    author: 'Рыбакова Елена',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gennaro_Gattuso_2008.jpg',
  },
  'Giggs': {
    file: 'giggs.jpg',
    author: 'James Adams',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ryan_Giggs_in_2008.jpg',
  },
  'Gilberto': {
    file: 'gilberto.jpg',
    author: 'Web Summit',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:2021_-_Press_conferences_SM7_0168_(51649502936)_(cropped).jpg',
  },
  'Guardiola': {
    file: 'guardiola.jpg',
    author: 'Steffen Prößdorf',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Josep_Guardiola_2023-10-04_Fu%C3%9Fball,_M%C3%A4nner,_UEFA_Champions_League,_RB_Leipzig_-_Manchester_City_FC_1DX_2797_(cropped).jpg',
  },
  'Hakimi': {
    file: 'hakimi.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg',
  },
  'Hargreaves': {
    file: 'hargreaves.jpg',
    author: 'Gordon Flood from Trim, Ireland',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:O_Hargreaves.jpg',
  },
  'Henderson': {
    file: 'henderson.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jordan_Henderson_England_v_Ghana_23_June_2026-029_(cropped).jpg',
  },
  'Henry': {
    file: 'henry.jpg',
    author: 'Web Summit',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Thierry_Henry_(51649035951)_(cropped).jpg',
  },
  'Iniesta': {
    file: 'iniesta.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Andr%C3%A9s_Iniesta_Argentina_v_Spain_19_July_2026-034_(cropped).jpg',
  },
  'Inzaghi': {
    file: 'inzaghi.jpg',
    author: 'Delfort',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Filippo_Inzaghi_2011.jpg',
  },
  'Irwin': {
    file: 'irwin.jpg',
    author: 'Kjetil Ree',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Denis_Irwin_(2017-07-29_img06)_(cropped).jpg',
  },
  'Isco': {
    file: 'isco.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Liver-RM_(5)_(cropped_2).jpg',
  },
  'Ivanović': {
    file: 'ivanovic.jpg',
    author: 'Вячеслав Евдокимов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Branislav_Ivanovi%C4%87_2020.jpg',
  },
  'Johnsen': {
    file: 'johnsen.jpg',
    author: 'Kjetil Ree',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ronny_Johnsen_(2017-07-29_img02).jpg',
  },
  'Júlio César': {
    file: 'julio-cesar.jpg',
    author: 'Майоров Владимир',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:J%C3%BAlio_C%C3%A9sar_FC_Internazionale.jpg',
  },
  'Kagawa': {
    file: 'kagawa.jpg',
    author: 'Кагава Синдзи',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Shinji_Kagawa_2018_(cropped).jpg',
  },
  'Kaká': {
    file: 'kaka.jpg',
    author: 'José Cruz/ABr (cropped by tales.ebner)',
    licence: 'CC BY 3.0 br',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0/br/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Ricardo_Izecson_dos_Santos_Leite_(Kak%C3%A1)_01.jpg',
  },
  'Keane': {
    file: 'keane.jpg',
    author: 'Irish Defence Forces from Ireland',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Roy_keane_2014.jpg',
  },
  'Koeman': {
    file: 'koeman.jpg',
    author: 'Richard Mulder',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ronald_Koeman_(2014)_(cropped).jpg',
  },
  'Kroos': {
    file: 'kroos.jpg',
    author: 'https://www.youtube.com/@realmadrid',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Toni_Kroos_Real_Madrid_2021.jpg',
  },
  'Kvaratskhelia': {
    file: 'kvaratskhelia.jpg',
    author: 'გიორგი კეკელიძის პირადი არქივი',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Khvicha_Kvaratskhelia_cropped.jpg',
  },
  'Lahm': {
    file: 'lahm.jpg',
    author: 'Elena Ternovaja',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Philipp_Lahm_auf_der_Berlinale_2024,_Ausschnitt.jpg',
  },
  'Lampard': {
    file: 'lampard.jpg',
    author: 'Mehdi Bolourian',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Frank_Lampard_2019.jpg',
  },
  'Lauren': {
    file: 'lauren.jpg',
    author: 'Chensiyuan',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:1_Laureano_Bisan_Etam%C3%A9-Mayer.jpg',
  },
  'Lehmann': {
    file: 'lehmann.jpg',
    author: 'Siebbi',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jens_Lehmann_(Berlin_Film_Festival_2011).jpg',
  },
  'Lewandowski': {
    file: 'lewandowski.jpg',
    author: 'Светлана Бекетова',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Robert_Lewandowski_2018,_JAP-POL_(cropped).jpg',
  },
  'Ljungberg': {
    file: 'ljungberg.jpg',
    author: 'Ricardo Alvarez',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fredrik_Ljungberg_2006.jpg',
  },
  'Lúcio': {
    file: 'lucio.jpg',
    author: 'Palácio do Planalto from Brasilia, Brasil',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Lucio_2019_(cropped).jpg',
  },
  'Maicon': {
    file: 'maicon.jpg',
    author: 'Steindy (talk) 23:39, 28 November 2009 (UTC)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Maicon_Douglas_Sisenando_-_Inter_Mailand_(2).jpg',
  },
  'Makélélé': {
    file: 'makelele.jpg',
    author: 'Web Summit Qatar',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Claude_Mak%C3%A9l%C3%A9l%C3%A9_(53557564951)_(cropped).jpg',
  },
  'Maldini': {
    file: 'maldini.jpg',
    author: 'Foad Ashtari',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Paolo_Maldini_press_conference_in_Tehran_(cropped).jpg',
  },
  'Malouda': {
    file: 'malouda.jpg',
    author: 'Stanislav Vedmid',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Malouda2012.JPG',
  },
  'Mané': {
    file: 'mane.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg',
  },
  'Maniche': {
    file: 'maniche.jpg',
    author: 'José Goulão from Lisbon, Portugal',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Portugal_2-3_Denmark,_Maniche.jpg',
  },
  'Marcelo': {
    file: 'marcelo.jpg',
    author: 'Granada',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Marcelo_850_1622.jpg',
  },
  'Marquinhos': {
    file: 'marquinhos.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Marquinhos_Brazil_V_Morocco_13_June_2026-153_(cropped).jpg',
  },
  'Martínez': {
    file: 'martinez.jpg',
    author: 'Rufus46',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Javi_Martinez_Training_2017-03_FC_Bayern_Muenchen-1_(cropped).jpg',
  },
  'Mascherano': {
    file: 'mascherano.jpg',
    author: 'Not credited',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Mascherano_casagob.jpg',
  },
  'Matip': {
    file: 'matip.jpg',
    author: 'Steffen Prößdorf',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:2022-07-21_Fu%C3%9Fball,_M%C3%A4nner,Freundschaftsspiel,_RB_Leipzig_-_FC_Liverpool_1DX_2092_by_Stepro_(cropped).jpg',
  },
  'Mendes': {
    file: 'mendes.jpg',
    author: 'Екатерина Лаут',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Pedro_Mendes_2018.jpg',
  },
  'Messi': {
    file: 'messi.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg',
  },
  'Mikel': {
    file: 'mikel.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:John_Obi_Mikel_2018.jpg',
  },
  'Milito': {
    file: 'milito.jpg',
    author: 'Steindy (talk) 13:14, 28 November 2009 (UTC)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Diego_Milito_-_Inter_Mailand_(3).jpg',
  },
  'Modrić': {
    file: 'modric.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Luka_Modric_Croatia_v_Portugal_2_July_2026-055.jpg',
  },
  'Müller': {
    file: 'muller.jpg',
    author: 'Werner100359',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Thomas_M%C3%BCller_2022_(cropped).jpg',
  },
  'Nadal': {
    file: 'nadal.jpg',
    author: 'Biser Todorov',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Miguel_Angel_Nadal_in_2016.jpg',
  },
  'Navas': {
    file: 'navas.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Keylor_Navas_2018_(cropped).jpg',
  },
  'Nesta': {
    file: 'nesta.jpg',
    author: 'Joerudi',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Alessandro_Nesta_as_Miami_FC_Manager.jpg',
  },
  'Neuer': {
    file: 'neuer.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Manuel_Neuer_Ecuador_v_Germany_25_June_2026-148.jpg',
  },
  'Neves': {
    file: 'neves.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jo%C3%A3o_Neves_USMNT_v_Portugal_Mar_31_2026-18_(cropped).jpg',
  },
  'Neymar': {
    file: 'neymar.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg',
  },
  'Nuno Mendes': {
    file: 'nuno-mendes.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Nuno_Mendes_Croatia_v_Portugal_2_July_2026-135_(cropped).jpg',
  },
  'Oddo': {
    file: 'oddo.jpg',
    author: 'Mech867',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Oddo_Perugia.jpg',
  },
  'Otamendi': {
    file: 'otamendi.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Nicolas_Otamendi_Argentina_v_Egypt_7_July_2026-030.jpg',
  },
  'P. Ferreira': {
    file: 'p-ferreira.jpg',
    author: '@cfcunofficial (Chelsea Debs) London',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Paulo_Ferreira_2017.jpg',
  },
  'Pacho': {
    file: 'pacho.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Willian_Pacho_Ecuador_v_Germany_25_June_2026-228.jpg',
  },
  'Pandev': {
    file: 'pandev.jpg',
    author: 'Новикова Юлия',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Goran_Pandev.JPG',
  },
  'Pedro': {
    file: 'pedro.jpg',
    author: 'Clément Bucco-Lechat',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bar%C3%A7a_-_Napoli_-_20140806_-_Pedro_Rodriguez_(cropped).jpg',
  },
  'Pepe': {
    file: 'pepe.jpg',
    author: 'Дмитрий Садовников',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Russia-Portugal_CC2017_(11_(cropped).jpg',
  },
  'Piqué': {
    file: 'pique.jpg',
    author: 'Vinod Divakaran',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:GerardPique.jpg',
  },
  'Pires': {
    file: 'pires.jpg',
    author: 'Zack',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Robert_Pir%C3%A8s.jpg',
  },
  'Pirlo': {
    file: 'pirlo.jpg',
    author: 'Clément Bucco-Lechat',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:20150616_-_Portugal_-_Italie_-_Gen%C3%A8ve_-_Andrea_Pirlo_(cropped).jpg',
  },
  'Puyol': {
    file: 'puyol.jpg',
    author: 'Darz Mol',
    licence: 'CC BY-SA 2.5 es',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.5/es/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Carles_Puyol_18abr2007.jpg',
  },
  'Rafael': {
    file: 'rafael.jpg',
    author: 'Andrea Sartorati',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Rafael_Man_Utd_2011.jpg',
  },
  'Rakitić': {
    file: 'rakitic.jpg',
    author: 'Дмитрий Пукалик',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ivan_Rakiti%C4%87_2020_(cropped).jpg',
  },
  'Ramos': {
    file: 'ramos.jpg',
    author: 'Real Madrid',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sergio_Ramos_Interview_2021_(cropped).jpg',
  },
  'Ribéry': {
    file: 'ribery.jpg',
    author: 'Sven Mandel',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Franck_Ribery_2019_(cropped).jpg',
  },
  'Robben': {
    file: 'robben.jpg',
    author: 'Дмитрий Садовников',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Arjen_Robben_2013.jpg',
  },
  'Robertson': {
    file: 'robertson.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Andy_Robertson_Scotland_v_Bolivia_6_June_2026-43.jpg',
  },
  'Romário': {
    file: 'romario.jpg',
    author: 'Agência Senado from Brasilia, Brazil',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Senadores_da_57%C2%AA_Legislatura_(52689451805).jpg',
  },
  'Ronaldo': {
    file: 'ronaldo.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_(cropped).jpg',
  },
  'Rooney': {
    file: 'rooney.jpg',
    author: 'Дмитрий Голубович',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Wayne-Rooney-2015-10-21.jpg',
  },
  'Ruiz': {
    file: 'ruiz.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fabian_Ruiz_Argentina_v_Spain_19_July_2026-315.jpg',
  },
  'Salah': {
    file: 'salah.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Mohamed_Salah_Argentina_v_Egypt_7_July_2026-163_(cropped).jpg',
  },
  'Samuel': {
    file: 'samuel.jpg',
    author: 'Steindy (talk) 17:05, 29 November 2009 (UTC)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Walter_Samuel_-_Inter_Mailand_(1).jpg',
  },
  'Sané': {
    file: 'sane.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Leroy_Sane_Ecuador_v_Germany_25_June_2026-004.jpg',
  },
  'Schmeichel': {
    file: 'schmeichel.jpg',
    author: 'Carlsberg',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Peter_Schmeichel_2012-01-25_001.jpg',
  },
  'Scholes': {
    file: 'scholes.jpg',
    author: 'James Adams',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:P_Scholes.jpg',
  },
  'Seedorf': {
    file: 'seedorf.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Clarence_Seedorf_2021.jpg',
  },
  'Sergi': {
    file: 'sergi.jpg',
    author: 'Dynamomania.com',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:%D0%A1%D0%B5%D1%80%D1%85%D1%96_%D0%91%D0%B0%D1%80%D1%85%D1%83%D0%B0%D0%BD_(cropped).jpg',
  },
  'Sneijder': {
    file: 'sneijder.jpg',
    author: 'Dmitry Neimyrok',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Wesley2012.JPG',
  },
  'Stam': {
    file: 'stam.jpg',
    author: 'Original: Flovries Derivative work: PeeJay2K3',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jaap_Stam_met_fan_cropped.jpg',
  },
  'Sterling': {
    file: 'sterling.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Raheem_Sterling_2018.jpg',
  },
  'Stoichkov': {
    file: 'stoichkov.jpg',
    author: 'Biso',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Hristo_stoichkov-2010.jpg',
  },
  'Stones': {
    file: 'stones.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:John_Stones_England_v_Ghana_23_June_2026-038.jpg',
  },
  'Suárez': {
    file: 'suarez.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Luis_Su%C3%A1rez_NE_Revolution_Inter_Miami_7.9.25-053_(cropped).jpg',
  },
  'Ter Stegen': {
    file: 'ter-stegen.jpg',
    author: 'Government of Catalonia',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Marc-Andre_Ter_Stegen_ACCI_FCBARCELONA_Turisme_Catalunya_gira_pretemporada_CATPRESS.jpg',
  },
  'Terry': {
    file: 'terry.jpg',
    author: 'ChristopherJClarke',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:John_Terry_at_pro-am_Wentworth_golf_course_September_2023_(cropped).jpg',
  },
  'Tévez': {
    file: 'tevez.jpg',
    author: 'Egghead06',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Carlos_Tevez_with_Argentina_November_2014_(cropped).jpg',
  },
  'Thiago': {
    file: 'thiago.jpg',
    author: 'Rolandhino1',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Thiago_Alcantara_13_(cropped).jpg',
  },
  'Tiago': {
    file: 'tiago.jpg',
    author: 'Carlos Delgado',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tiago_Mendes_-_01.jpg',
  },
  'Touré': {
    file: 'toure.jpg',
    author: 'Ailura',
    licence: 'CC BY-SA 3.0 at',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/at/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Kolo_Toure_8932.JPG',
  },
  'Valdés': {
    file: 'valdes.jpg',
    author: 'Дмитрий Неймырок',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:V%C3%ADctor_Vald%C3%A9s_before_Euro_2012_vs_France_(cropped).jpg',
  },
  'Valencia': {
    file: 'valencia.jpg',
    author: 'Julia Novikova for Soccer.ru',
    licence: 'CC BY-SA 1.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/1.0',
    source: 'https://commons.wikimedia.org/wiki/File:Antonio_Valencia_cropped.jpg',
  },
  'Van der Sar': {
    file: 'van-der-sar.jpg',
    author: 'Paul Blank',
    licence: 'CC BY 2.5',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.5',
    source: 'https://commons.wikimedia.org/wiki/File:Edwin_van_der_Sar_side.jpg',
  },
  'Van Dijk': {
    file: 'van-dijk.jpg',
    author: 'Ailura',
    licence: 'CC BY-SA 3.0 at',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/at/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:20160604_AUT_NED_8876_(cropped).jpg',
  },
  'Van Persie': {
    file: 'van-persie.jpg',
    author: 'Елена Рыбакова',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Loco-Fener_(10).jpg',
  },
  'Varane': {
    file: 'varane.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Liver-RM_(8)_(Varane).jpg',
  },
  'Vidić': {
    file: 'vidic.jpg',
    author: 'Austin Osuide',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Nemanja_Vidi%C4%87.jpg',
  },
  'Vieira': {
    file: 'vieira.jpg',
    author: 'Simon Heseltine',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Patrick_Vieira_NYCFC.JPG',
  },
  'Villa': {
    file: 'villa.jpg',
    author: 'Tânia Rêgo/ABr',
    licence: 'CC BY 3.0 br',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0/br/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Spain-Tahiti,_Confederations_Cup_2013_(02)_(Villa_crop).jpg',
  },
  'Vitinha': {
    file: 'vitinha.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Vitinha_USMNT_v_Portugal_Mar_31_2026-50_(cropped).jpg',
  },
  'Vítor Baía': {
    file: 'vitor-baia.jpg',
    author: 'Christophe95',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:V%C3%ADtor_Ba%C3%ADa.JPG',
  },
  'Walker': {
    file: 'walker.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kyle_Walker.jpg',
  },
  'Wijnaldum': {
    file: 'wijnaldum.jpg',
    author: 'Ailura',
    licence: 'CC BY-SA 3.0 at',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/at/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:20160604_AUT_NED_8839.jpg',
  },
  'Xabi Alonso': {
    file: 'xabi-alonso.jpg',
    author: 'DONOSTIA KULTURA',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Los_Caminos_del_f%C3%BAtbol._Xabi_Alonso_(39666778464)_(cropped).jpg',
  },
  'Xavi': {
    file: 'xavi.jpg',
    author: 'Mehdi Zare',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Xavi_13981129001173637176666027076571.jpg',
  },
  'Yorke': {
    file: 'yorke.jpg',
    author: 'Deepti Soni',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dwight_Yorke_in_Chennai.jpg',
  },
  'Zanetti': {
    file: 'zanetti.jpg',
    author: 'Давиденко Валерий',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Javier_Adelmar_Zanetti.jpg',
  },
  'Zubizarreta': {
    file: 'zubizarreta.jpg',
    author: 'Pepito',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Andoni_Zubizarreta.jpg',
  },
  "Jankulovski": {
    file: "jankulovski.jpg",
    author: "Tadeáš Bednarz",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Marek_Jankulovski_Jablonec-Ostrava.jpg",
  },
  "Raya": {
    file: "raya.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:David_Raya_Argentina_v_Spain_19_July_2026-003_(cropped).jpg",
  },
  "Zinchenko": {
    file: "zinchenko.jpg",
    author: "Steffen Prößdorf",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:2021-12-07_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2777_by_Stepro.jpg",
  },
  "Gabriel": {
    file: "gabriel.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Gabriel_Magalhaes_Brazil_V_Morocco_13_June_2026-132_(cropped).jpg",
  },
  "White": {
    file: "white.jpg",
    author: "James Boyes from UK",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Ben_White_2018.jpg",
  },
  "Rice": {
    file: "rice.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Declan_Rice_England_v_Ghana_23_June_2026-150.jpg",
  },
  "Ødegaard": {
    file: "degaard.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Martin_Odegaard_Morocco_v_Norway_7_June_2026-56_(cropped).jpg",
  },
  "Havertz": {
    file: "havertz.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kai_Havertz_Ecuador_v_Germany_25_June_2026-118.jpg",
  },
  "Saka": {
    file: "saka.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bukayo_Saka_England_v_Ghana_23_June_2026-057_(cropped).jpg",
  },
  "Sergio Rico": {
    file: "sergio-rico.jpg",
    author: "Solent Creatives from Southampton, United KIngdom",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Southampton_FC_versus_Sevilla_(36254441351)_(cropped).jpg",
  },
  "Rami": {
    file: "rami.jpg",
    author: "Stanislav Vedmid",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Adil_Rami_20120611.jpg",
  },
  "Carriço": {
    file: "carrico.jpg",
    author: "Вячеслав Евдокимов",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Zenit-Sevilla_(12).jpg",
  },
  "Mariano": {
    file: "mariano.jpg",
    author: "Romain Dagbert",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mariano_Ferreira_Filho.jpg",
  },
  "Banega": {
    file: "banega.jpg",
    author: "Aleksandr Osipov from Ukraine",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:05-05-2016_-_Sevilla_FC_-_FC_Shakhtar_Donetsk_-_3-1_%C3%89ver_Maximiliano_David_Banega.jpg",
  },
  "Konoplyanka": {
    file: "konoplyanka.jpg",
    author: "Oleg Dubyna (Олег Дубина)",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Yevhen_Konoplianka.jpg",
  },
  "Digne": {
    file: "digne.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Lucas_Digne_France_v_Norway_26_June_26-043.jpg",
  },
  "Pau Torres": {
    file: "pau-torres.jpg",
    author: "MintyGel",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pau_Torres_April_2026_(cropped).jpg",
  },
  "Konsa": {
    file: "konsa.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ezri_Konsa_England_v_Panama_27_June_26-259_(cropped).jpg",
  },
  "Bailey": {
    file: "bailey.jpg",
    author: "Fuguito",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Leon_Bailey_bei_der_Saisoneroeffnung_August_2018.jpg",
  },
  "Kamara": {
    file: "kamara.jpg",
    author: "Supporterhéninois",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Lens_-_Marseille_(22-01-2022)_17.jpg",
  },
  "McGinn": {
    file: "mcginn.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:John_McGinn_Scotland_v_Bolivia_6_June_2026-3.jpg",
  },
  "Watkins": {
    file: "watkins.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ollie_Watkins_England_v_Ghana_23_June_2026-035.jpg",
  },
  "Diaby": {
    file: "diaby.jpg",
    author: "Pyaet",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Moussa_Diaby%2C_2022-07-31%2C_Saisoner%C3%B6ffnung_Bayer_04%2C_Leverkusen_(1).jpg",
  },
  "Hrádecký": {
    file: "hradecky.jpg",
    author: "Fuguito",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Luk%C3%A1%C5%A1_Hr%C3%A1deck%C3%BD_August_2018.jpg",
  },
  "Tah": {
    file: "tah.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Jonathan_Tah_Ecuador_v_Germany_25_June_2026-116.jpg",
  },
  "Tapsoba": {
    file: "tapsoba.jpg",
    author: "Pyaet",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Edmond_Tapsoba%2C_2022-07-31%2C_Saisoner%C3%B6ffnung_Bayer_04%2C_Leverkusen_(1)_(cropped).jpg",
  },
  "Grimaldo": {
    file: "grimaldo.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Alex_Grimaldo_Argentina_v_Spain_19_July_2026-314.jpg",
  },
  "Palacios": {
    file: "palacios.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Exequiel_Palacios_Argentina_v_Spain_19_July_2026-022.jpg",
  },
  "Anelka": {
    file: "anelka.jpg",
    author: "Amarhgil",
    licence: "Attribution",
    licenceUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    source: "https://commons.wikimedia.org/wiki/File:Nicolas_Anelka_4720.jpg",
  },
  "Saliba": {
    file: "saliba.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:William_Saliba_France_v_Senegal_16_June_2026-336_(cropped).jpg",
  },
  "Martinelli": {
    file: "martinelli.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Gabriel_Martinelli_Brazil_V_Morocco_13_June_2026-144.jpg",
  },
  "Escudero": {
    file: "escudero.jpg",
    author: "Memorino",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Sergio_Escudero.jpg",
  },
  "Gameiro": {
    file: "gameiro.jpg",
    author: "Aleksandr Osipov from Ukraine",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Kevin_Gameiro_2016_(cropped).jpg",
  },
  "Cash": {
    file: "cash.jpg",
    author: "Nottingham Forest F.C.",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Matty_Cash_(cropped).jpg",
  },
  "Tielemans": {
    file: "tielemans.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Youri_Tielemans_USMNT_v_Belgium_Mar_28_2026-20_(cropped).jpg",
  },
  "Xhaka": {
    file: "xhaka.jpg",
    author: "@cfcunofficial (Chelsea Debs) London from London, UK",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Granit_Xhaka_(cropped).jpg",
  },
  "Frimpong": {
    file: "frimpong.jpg",
    author: "Timmy96",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Jeremie_Frimpong_04012026_(3)_(cropped).jpg",
  },
  "Wirtz": {
    file: "wirtz.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Florian_Wirtz_Ecuador_v_Germany_25_June_2026-181_(cropped).jpg",
  },
  "Boniface": {
    file: "boniface.jpg",
    author: "Yoroudhgd",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Boniface_Jr.jpg",
  },
  "Adán": {
    file: "adan.jpg",
    author: "Анна Нэсси",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Antonio_Ad%C3%A1n.jpg",
  },
  "Matheus Reis": {
    file: "matheus-reis.jpg",
    author: "User:RickMorais",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:MatheusReis2021.png",
  },
  "Diomande": {
    file: "diomande.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ousmane_Diomand%C3%A9_Cote_D'Ivoire_v_Ecuador_14_June_2026-58.jpg",
  },
  "Hjulmand": {
    file: "hjulmand.jpg",
    author: "Steindy (talk) 23:15, 4 September 2018 (UTC)",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Morten_Hjulmand%2C_FC_Admira_Wacker_M%C3%B6dling_vs._LASK_Linz_2018-08-12.jpg",
  },
  "Morita": {
    file: "morita.jpg",
    author: "阿文",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:%E5%AE%88%E7%94%B0%E8%8B%B1%E6%AD%A3_(cropped).jpg",
  },
  "Trincão": {
    file: "trincao.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Francisco_Trinc%C3%A3o_USMNT_v_Portugal_Mar_31_2026-55_(cropped).jpg",
  },
  "Gyökeres": {
    file: "gyokeres.jpg",
    author: "Mikael Hervestad",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Viktor_Gy%C3%B6keres_2026-06-04_1_(cropped)_1.jpg",
  },
  "Davies": {
    file: "davies.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Alphonso_Davies_Canada_v_Qatar_18_June_2026-007_(cropped).jpg",
  },
  "Kimmich": {
    file: "kimmich.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Joshua_Kimmich_Ecuador_v_Germany_25_June_2026-149.jpg",
  },
  "Goretzka": {
    file: "goretzka.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Leon_Goretzka_Ecuador_v_Germany_25_June_2026-159.jpg",
  },
  "Gnabry": {
    file: "gnabry.jpg",
    author: "Steffen Prößdorf",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:2019-06-11_Fu%C3%9Fball%2C_M%C3%A4nner%2C_L%C3%A4nderspiel%2C_Deutschland-Estland_StP_2075_LR10_by_Stepro.jpg",
  },
  "Courtois": {
    file: "courtois.jpg",
    author: "Кирилл Венедиктов",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Thibaut_Courtois_at_the_2018_World_Cup_(cropped).jpg",
  },
  "Filipe Luís": {
    file: "filipe-luis.jpg",
    author: "Светлана Бекетова",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Filipe_Lu%C3%ADs_2018.jpg",
  },
  "Godín": {
    file: "godin.jpg",
    author: "Анна Нэсси",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Diego_God%C3%ADn_2018_(cropped).jpg",
  },
  "Juanfran": {
    file: "juanfran.jpg",
    author: "Giovanni Batista Rodriguez from San Sebastian-Donostia, España",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:JF_(17126673351)_(cropped).jpg",
  },
  "Arda Turan": {
    file: "arda-turan.jpg",
    author: "ФК \"Карпати\" Львів",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:%D0%90%D1%80%D0%B4%D0%B0_%D0%A2%D1%83%D1%80%D0%B0%D0%BD.webp",
  },
  "Oblak": {
    file: "oblak.jpg",
    author: "Анна Нэсси",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Jan_Oblak_2019.jpg",
  },
  "Hermoso": {
    file: "hermoso.jpg",
    author: "Giovanni Batista Rodriguez from San Sebastian-Donostia, España",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Mario_Hermoso.jpg",
  },
  "Giménez": {
    file: "gimenez.jpg",
    author: "Анна Нэсси",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Jos%C3%A9_Mar%C3%ADa_Gim%C3%A9nez_(cropped).jpg",
  },
  "Carrasco": {
    file: "carrasco.jpg",
    author: "Светлана Бекетова",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Yannick_Ferreira_Carrasco_(cropped).jpg",
  },
  "Saúl": {
    file: "saul.jpg",
    author: "Кирилл Венедиктов",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Sa%C3%BAl_%C3%91%C3%ADguez_2021.jpg",
  },
  "Llorente": {
    file: "llorente.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Marcos_Llorente_France_v_Spain_7.24.26-020.jpg",
  },
  "João Félix": {
    file: "joao-felix.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Joao_Felix_Croatia_v_Portugal_2_July_2026-007.jpg",
  },
  "Upamecano": {
    file: "upamecano.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Dayot_Upamecano_France_v_Senegal_16_June_2026-402_(cropped).jpg",
  },
  "Laimer": {
    file: "laimer.jpg",
    author: "Steffen Prößdorf",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:2022-07-21_Fu%C3%9Fball%2C_M%C3%A4nner%2CFreundschaftsspiel%2C_RB_Leipzig_-_FC_Liverpool_1DX_2137_by_Stepro_(cropped).jpg",
  },
  "Musiala": {
    file: "musiala.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Jamal_Musiala_Ecuador_v_Germany_25_June_2026-174_(cropped).jpg",
  },
  "Olise": {
    file: "olise.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Michael_Olise_France_v_Senegal_16_June_2026-307_(cropped).jpg",
  },
  "Kane": {
    file: "kane.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Harry_Kane_England_v_Ghana_23_June_2026-219_(cropped).jpg",
  },
  "Kimpembe": {
    file: "kimpembe.jpg",
    author: "Miroslav Lelas/PIXSELL",
    licence: "CC BY 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Presnel_Kimpembe_2022.jpg",
  },
  "Thiago Silva": {
    file: "thiago-silva.jpg",
    author: "Granada",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Thiago_Silva_850_1582.jpg",
  },
  "Kehrer": {
    file: "kehrer.jpg",
    author: "Steffen Prößdorf",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:2019-06-11_Fu%C3%9Fball%2C_M%C3%A4nner%2C_L%C3%A4nderspiel%2C_Deutschland-Estland_StP_2073_LR10_by_Stepro.jpg",
  },
  "Gueye": {
    file: "gueye.jpg",
    author: "Екатерина Лаут",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Idrissa_Gueye_(cropped).jpg",
  },
  "Mbappé": {
    file: "mbappe.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kylian_Mbappe_France_v_Senegal_16_June_2026-391_(cropped).jpg",
  },
  "Mendy": {
    file: "mendy.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Edouard_Mendy_France_v_Senegal_16_June_2026-375_(cropped).jpg",
  },
  "Azpilicueta": {
    file: "azpilicueta.jpg",
    author: "محمد امین انصاری",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:C%C3%A9sar_Azpilicueta%2C_Al_Hilal_SFC_vs_Chelsea_F.C.%2C_9_February_2022.jpg",
  },
  "Chilwell": {
    file: "chilwell.jpg",
    author: "Дмитрий Пукалик",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Ben_Chilwell_2020.jpg",
  },
  "Kanté": {
    file: "kante.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:N'Golo_Kante_France_v_Senegal_16_June_2026-397.jpg",
  },
  "Mount": {
    file: "mount.jpg",
    author: "Brian Minkoff London-Pixels",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mountbrightonoct3_2019_(cropped).jpg",
  },
  "Werner": {
    file: "werner.jpg",
    author: "Steffen Prößdorf",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3684_by_Stepro.jpg",
  },
  "Capdevila": {
    file: "capdevila.jpg",
    author: "Christophe95",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Joan_Capdevila_2010.jpg",
  },
  "Senna": {
    file: "senna.jpg",
    author: "Delatorre",
    licence: "CC BY 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Senna1.jpg",
  },
  "Fàbregas": {
    file: "fabregas.jpg",
    author: "Web Summit",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:2023_-_Cesc_Fabregas_(cropped).jpg",
  },
  "Silva": {
    file: "silva.jpg",
    author: "Дмитрий Неймырок",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:David_Silva_Euro_2012_vs_France_01.jpg",
  },
  "Dudek": {
    file: "dudek.jpg",
    author: "Ja Fryta from Strzegom",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Jerzy_Dudek_(2)_(rotated).jpg",
  },
  "Hyypiä": {
    file: "hyypia.jpg",
    author: "Дмитрий Неймырок/Dmitry Neymyrok/Dmitrij Nejmyrok",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Sami_Hyypia_2012.jpg",
  },
  "Finnan": {
    file: "finnan.jpg",
    author: "Alii h at English Wikipedia",
    licence: "Public domain",
    licenceUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    source: "https://commons.wikimedia.org/wiki/File:Finnan.jpg",
  },
  "Riise": {
    file: "riise.jpg",
    author: "Jarvin",
    licence: "CC BY-SA 3.0",
    licenceUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:John_Arne_Riise2.JPG",
  },
  "Gerrard": {
    file: "gerrard.jpg",
    author: "Эдгар Брещанов",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Steven_Gerrard_2018.jpg",
  },
  "Baroš": {
    file: "baros.jpg",
    author: "Tadeáš Bednarz",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Milan_Baro%C5%A13%2C_FCB-SLAVIA_30092018.jpg",
  },
  "Kewell": {
    file: "kewell.jpg",
    author: "Kevin Airs",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:HarryKewell.jpg",
  },
  "Rossi": {
    file: "rossi.jpg",
    author: "Vecchiaguardia at Italian Wikipedia",
    licence: "CC BY-SA 3.0",
    licenceUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Sebastiano_Rossi.jpg",
  },
  "Costacurta": {
    file: "costacurta.jpg",
    author: "F1fans",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Billy_Costacurta_AC_Milan_Glorie_2011.jpg",
  },
  "Tassotti": {
    file: "tassotti.jpg",
    author: "goatling",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Mauro_Tassotti_(cropped).jpg",
  },
  "Boban": {
    file: "boban.jpg",
    author: "Russian Presidential Press and Information Office",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Zvonimir_Boban_in_2018.jpg",
  },
  "Albertini": {
    file: "albertini.jpg",
    author: "User:Mbx",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Demetrio_Albertini.JPG",
  },
  "Donadoni": {
    file: "donadoni.jpg",
    author: "Steindy (talk) 13:14, 26 July 2009 (UTC)",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Roberto_Donadoni_-_SSC_Neapel_(2)_(cropped).jpg",
  },
  "Massaro": {
    file: "massaro.jpg",
    author: "User:Mbx",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Daniele_Massaro.JPG",
  },
  "Grobbelaar": {
    file: "grobbelaar.jpg",
    author: "Jarvin",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Bruce_Grobbelaar.png",
  },
  "Hansen": {
    file: "hansen.jpg",
    author: "User:Snowmanradio",
    licence: "CC BY-SA 3.0",
    licenceUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Alan_hansen_in_2004.png",
  },
  "Nicol": {
    file: "nicol.jpg",
    author: "RevsTV",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Steve_Nicol_at_the_2005_MLS_SuperDraft_(cropped).jpg",
  },
  "Barnes": {
    file: "barnes.jpg",
    author: "Sjur Bjørkly",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:John_Barnes_in_Kristiansund%2C_Norway.jpg",
  },
  "McMahon": {
    file: "mcmahon.jpg",
    author: "petetambo",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Steve_McMahon.jpg",
  },
  "Whelan": {
    file: "whelan.jpg",
    author: "Jarvin",
    licence: "CC BY 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Ronnie_Whelan.JPG",
  },
  "Beardsley": {
    file: "beardsley.jpg",
    author: "Skippo10",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Beardsley%2C_Peter.jpg",
  },
  "Aldridge": {
    file: "aldridge.jpg",
    author: "Jarvin",
    licence: "CC BY 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:John_Aldridge.JPG",
  },
  "Schweinsteiger": {
    file: "schweinsteiger.jpg",
    author: "Anne Barth  /  re:publica",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Re-publica_23_-_Tag_3_(52957826298)_(cropped).jpg",
  },
  "Mandžukić": {
    file: "mandzukic.jpg",
    author: "Антон Зайцев",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Mario_Mand%C5%BEuki%C4%87_in_2018.jpg",
  },
  "Buffon": {
    file: "buffon.jpg",
    author: "Original:  Doha Stadium Plus Qatar from Doha, Qatar\nDerivative work:  Alza08\nAuthor",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Gianluigi_Buffon_(31784615942)_(cropped).jpg",
  },
  "Grosso": {
    file: "grosso.jpg",
    author: "Original:  Antonio Fraioli\nDerivative work:  Lorenzo De Leonardis2",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Fabio_Grosso_-_Frosinone_Calcio_-_DSC_2731_AF_(cropped).jpg",
  },
  "Materazzi": {
    file: "materazzi.jpg",
    author: "Анна Нэсси",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Marco_Materazzi_2020.jpg",
  },
  "Zambrotta": {
    file: "zambrotta.jpg",
    author: "Кирилл Венедиктов",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Gianluca_Zambrotta_2019.jpg",
  },
  "Perrotta": {
    file: "perrotta.jpg",
    author: "Gaúcho",
    licence: "Public domain",
    licenceUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    source: "https://commons.wikimedia.org/wiki/File:Simone_Perrotta_2007.jpg",
  },
  "Totti": {
    file: "totti.jpg",
    author: "Photojournalist Roberto Vicario\n\nderivative work: Clarus The Dogcow (talk)",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Francesco_Totti_Vicario_(crop).jpg",
  },
  "Toni": {
    file: "toni.jpg",
    author: "Kirill Venediktov",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:FC_Zenit_Saint_Petersburg_vs._Juventus%2C_20_October_2021_33_(Luca_Toni).jpg",
  },
  "Jongbloed": {
    file: "jongbloed.jpg",
    author: "Anefo / Croes, R.C.",
    licence: "CC BY-SA 3.0 nl",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Jan_Jongbloed_1984.jpg",
  },
  "Haan": {
    file: "haan.jpg",
    author: "Hans Peters for Anefo",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Arie_Haan_1978c.jpg",
  },
  "Rijsbergen": {
    file: "rijsbergen.jpg",
    author: "Rob Croes for Anefo",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Persdag_FC_Utrecht_Wim_Rijsbergen%2C_Bestanddeelnr_933-0411.jpg",
  },
  "Suurbier": {
    file: "suurbier.jpg",
    author: "Hans Peters for Anefo",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Persdag_bij_Ajax._Wim_Suurbier%2C_Bestanddeelnr_928-6997.jpg",
  },
  "Jansen": {
    file: "jansen.jpg",
    author: "Christophe95",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Wim_Jansen_2013.jpg",
  },
  "Neeskens": {
    file: "neeskens.jpg",
    author: "Mieremet, Rob / Anefo",
    licence: "CC BY-SA 3.0 nl",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Johan_Neeskens_1974.jpg",
  },
  "Rensenbrink": {
    file: "rensenbrink.jpg",
    author: "Hans Peters for Anefo , Nationaal Archief, Den Haag, Rijksfotoarchief: Fotocollectie Algem",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Rob_Rensenbrink_(1978).jpg",
  },
  "Rep": {
    file: "rep.jpg",
    author: "Paul Blank",
    licence: "CC BY 2.5",
    licenceUrl: "https://creativecommons.org/licenses/by/2.5",
    source: "https://commons.wikimedia.org/wiki/File:John_Rep.jpg",
  },
  "Clemence": {
    file: "clemence.jpg",
    author: "Marcel Antonisse / Anefo",
    licence: "CC BY-SA 3.0 nl",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ray_Clemence_(1981).jpg",
  },
  "Hughes": {
    file: "hughes.jpg",
    author: "Comet Photo AG (Zürich)",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Emlyn_Hughes_(cropped).jpg",
  },
  "Neal": {
    file: "neal.jpg",
    author: "Eddie Janssens",
    licence: "CC BY 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Phil-neal-1338116110.jpg",
  },
  "Kennedy": {
    file: "kennedy.jpg",
    author: "Fotograaf Hans van Dijk / Anefo",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ray_Kennedy1.jpg",
  },
  "Callaghan": {
    file: "callaghan.jpg",
    author: "Eric Koch for Anefo",
    licence: "CC BY-SA 3.0 nl",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ian_Callaghan_(1966).jpg",
  },
  "Heighway": {
    file: "heighway.jpg",
    author: "ETH-Bibliothek Zürich, Bildarchiv / Fotograf: Comet Photo AG (Zürich) / Com_LC1432-000-005",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:FC_Z%C3%BCrich_against_Liverpool_-_Steve_Heighway_(cropped).jpg",
  },
  "Keegan": {
    file: "keegan.jpg",
    author: "Unknown authorUnknown author",
    licence: "Public domain",
    licenceUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    source: "https://commons.wikimedia.org/wiki/File:Kevin_keegan_panini_card_(cropped).jpg",
  },
  "McDermott": {
    file: "mcdermott.jpg",
    author: "Rob Bogaerts / Anefo",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Amsterdam_702_voetbaltoernooi_Ajax_tegen_Liverpool%2C_Geels_springt_mee_met_doelm%2C_Bestanddeelnr_929-2965_(Terry_McDermott).jpg",
  },
  "Rijkaard": {
    file: "rijkaard.jpg",
    author: "Marcel Antonisse / Anefo",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ajax_selectie_seizoen_1981_1982_nr._140a_E._Ophof_speler%2C_nr._15a_F._Rijka%2C_Bestanddeelnr_253-8568.jpg",
  },
  "Ancelotti": {
    file: "ancelotti.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Carlo_Ancelotti_Brazil_V_Morocco_13_June_2026-47.jpg",
  },
  "Gullit": {
    file: "gullit.jpg",
    author: "Barcex",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:25th_Laureus_World_Sports_Awards_-_Ruud_Gullit_-_240422_131911_(cropped).jpg",
  },
  "Yeats": {
    file: "yeats.jpg",
    author: "Migrant",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:RonYeats-Oslo-12oct2007.jpg",
  },
  "Stevenson": {
    file: "stevenson.jpg",
    author: "Eric Koch for Anefo",
    licence: "CC BY-SA 3.0 nl",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Willie_Stevenson_(1966).jpg",
  },
  "Milne": {
    file: "milne.jpg",
    author: "Eric Koch for Anefo",
    licence: "CC BY-SA 3.0 nl",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Gordon_Milne_(1966).jpg",
  },
  "St John": {
    file: "st-john.jpg",
    author: "Eric Koch for Anefo",
    licence: "CC BY-SA 3.0 nl",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ian_St_John_(1966).jpg",
  },
  "Krychowiak": {
    file: "krychowiak.jpg",
    author: "Антон Зайцев",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Krychowiak_in_2020.jpg",
  },
  "Hincapié": {
    file: "hincapie.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Piero_Hincapie_Cote_D'Ivoire_v_Ecuador_14_June_2026-247_(cropped).jpg",
  },
  "Hofmann": {
    file: "hofmann.jpg",
    author: "Eastfrisian",
    licence: "CC BY 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Jonas_Hofmann_2013_in_Wilhelmshaven.jpeg",
  },
  "Coates": {
    file: "coates.jpg",
    author: "Anthony Booker",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Sebastian_Coates_-_Olympics_2012.jpg",
  },
  "Pavard": {
    file: "pavard.jpg",
    author: "Кирилл Венедиктов",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Benjamin_Pavard_20180709.jpg",
  },
  "Coman": {
    file: "coman.jpg",
    author: "Sven Mandel",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kingsley_Coman_(2019)_(cropped).jpg",
  },
  "Diego Costa": {
    file: "diego-costa.jpg",
    author: "Mahdi Zare/Fars News Agency",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Iran_and_Spain_match_at_the_FIFA_World_Cup_23.jpg",
  },
  "Savić": {
    file: "savic.jpg",
    author: "Дмитрий Садовников",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Ros-che_25.jpg",
  },
  "Pavlović": {
    file: "pavlovic.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Aleksandar_Pavlovic_Ecuador_v_Germany_25_June_2026-036.jpg",
  },
  "Bernat": {
    file: "bernat.jpg",
    author: "Victor Guttiérrez Navarro",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bernat-VCF_vs_ESP-2012.jpg",
  },
  "Herrera": {
    file: "herrera.jpg",
    author: "Sandro Halank, Wikimedia Commons",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:2019-07-17_SG_Dynamo_Dresden_vs._Paris_Saint-Germain_by_Sandro_Halank%E2%80%93282_(cropped).jpg",
  },
  "James": {
    file: "james.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Reece_James_England_v_Ghana_23_June_2026-248_(cropped).jpg",
  },
  "Marchena": {
    file: "marchena.jpg",
    author: "Steindy (talk) 13:11, 13 July 2010 (UTC)",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Carlos_Marchena.jpg",
  },
  "Torres": {
    file: "torres.jpg",
    author: "cristina cifuentes",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Fernando_Torres_2017.jpg",
  },
  "Carragher": {
    file: "carragher.jpg",
    author: "Ludovic Péron",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Football_against_poverty_2014_-_Jamie_Carragher_(cropped).jpg",
  },
  "Luis García": {
    file: "luis-garcia.jpg",
    author: "Chin Yu Chu",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Luis_Garc%C3%ADa_Sanz_-_53690670543.jpg",
  },
  "Galli": {
    file: "galli.jpg",
    author: "Roberto Vicario",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Giovanni_galli.JPG",
  },
  "Savićević": {
    file: "savicevic.jpg",
    author: "Christophe95",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Dejan_Savi%C4%87evi%C4%87.jpg",
  },
  "Dante": {
    file: "dante.jpg",
    author: "Paté kroute",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Dante_asse_ogcn_2425.png",
  },
  "Javi Martínez": {
    file: "javi-martinez.jpg",
    author: "Rufus46",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Javi_Martinez_Training_2017-03_FC_Bayern_Muenchen-1_(cropped).jpg",
  },
  "Cannavaro": {
    file: "cannavaro.jpg",
    author: "Original:  Mech867 / Derivative work:  Danyele",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Fabio_Cannavaro_-_2024_(cropped).jpg",
  },
  "Krol": {
    file: "krol.jpg",
    author: "Christophe95",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Ruud_Krol_2005.jpg",
  },
  "van Hanegem": {
    file: "van-hanegem.jpg",
    author: "Luctor",
    licence: "Public domain",
    licenceUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    source: "https://commons.wikimedia.org/wiki/File:VanHanegem.jpg",
  },
  "Cruyff": {
    file: "cruyff.jpg",
    author: "Rob Mieremet / Anefo",
    licence: "CC0",
    licenceUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Johan_Cruijff_(1974).jpg",
  },
  "Case": {
    file: "case.jpg",
    author: "Dudek1337",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Jimmy_Case_2024.jpg",
  },
  "Baresi": {
    file: "baresi.jpg",
    author: "Unknown authorUnknown author",
    licence: "Public domain",
    licenceUrl: "https://commons.wikimedia.org/wiki/Commons:Licensing",
    source: "https://commons.wikimedia.org/wiki/File:Franco_baresi_panini_card_1979.jpg",
  },
  "Lawrence": {
    file: "lawrence.jpg",
    author: "Eric Koch for Anefo",
    licence: "CC BY-SA 3.0 nl",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Tommy_Lawrence_(1966).jpg",
  },
  "Byrne": {
    file: "byrne.jpg",
    author: "Christophe95",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Gerry_Byrne.jpg",
  },
  "Lawler": {
    file: "lawler.jpg",
    author: "Migrant",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:ChrisLawler-Oslo-12oct2007.jpg",
  },
  "Miranda": {
    file: "miranda.jpg",
    author: "Granada",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Miranda_850_1585.jpg",
  },
  "Kim": {
    file: "kim.jpg",
    author: "Werner100359",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:FC_Red_Bull_Salzburg_gegen_Bayern_M%C3%BCnchen_(2025-01-06_Testspiel)_26.jpg",
  },
  "Rüdiger": {
    file: "rudiger.jpg",
    author: "Bryan Berlin",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Antonio_Rudiger_Ecuador_v_Germany_25_June_2026-055_(cropped).jpg",
  },
  "Houghton": {
    file: "houghton.jpg",
    author: "Ben Sutherland",
    licence: "CC BY 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Ray_Houghton_1995.jpg",
  },
  "Camoranesi": {
    file: "camoranesi.jpg",
    author: "Biser Todorov",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Camoranesi_2016.jpg",
  },
  "Van Basten": {
    file: "van-basten.jpg",
    author: "Paul Blank - Postproduktie.nl",
    licence: "CC BY 2.5",
    licenceUrl: "https://creativecommons.org/licenses/by/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Marco_van_Basten_(ca_2006).jpg",
  },
  "Hunt": {
    file: "hunt.jpg",
    author: "Christophe95",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Roger_Hunt.jpg",
  },
  "Jorginho": {
    file: "jorginho.jpg",
    author: "محمد امین انصاری",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:2021_FIFA_Club_World_Cup_Final_-_01_(Jorginho_com_a_medalha_do_Mundial_de_Clubes).jpg",
  },
  "Koke": {
    file: "koke.jpg",
    author: "Анна Нэсси",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Koke_2019.jpg",
  },
  "Vitolo": {
    file: "vitolo.jpg",
    author: "Aleksandr Osipov from Ukraine",
    licence: "CC BY-SA 2.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:V%C3%ADctor_Vitolo.jpg",
  },
  "Nuno Santos": {
    file: "nuno-santos.jpg",
    author: "Studium Creative Co",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Portrait_-_Nuno_Santos.jpg",
  },
  "Trippier": {
    file: "trippier.jpg",
    author: "Кирилл Венедиктов",
    licence: "CC BY-SA 3.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Kieran_Trippier_2018-07-14_1.jpg",
  },
  "Desailly": {
    file: "desailly.jpg",
    author: "Barcex",
    licence: "CC BY-SA 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Marcel_Desailly_-_240422_192752-3_(cropped).jpg",
  },
  "Jones": {
    file: "jones.jpg",
    author: "ETH-Bibliothek Zürich, Bildarchiv / Fotograf: Comet Photo AG (Zürich) / Com_LC1432-000-012",
    licence: "CC BY 4.0",
    licenceUrl: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Joey_Jones.png",
  },
};

export const playerPhotoUrl = (file: string) => `${import.meta.env.BASE_URL}players/${file}`;
