// Player portraits, keyed by the short name used in each era's XI.
//
// Each player is resolved through Wikidata rather than an image search: the
// entity must be a human (P31=Q5) whose occupation is footballer or manager
// (P106), and we take that entity's canonical image (P18). That matters —
// a plain Commons text search returned the wrong people entirely (a USA
// women's international for "Lauren", the 1960s Spaniard for "Suárez", and
// Fredy Guarín for "Maicon"), because it matches filenames, not identities.
//
// Every image is CC0/CC BY/CC BY-SA, all of which require visible credit, so
// the inspector renders the photographer, licence and source link beside the
// portrait — do not remove that. Players absent from this map (no free image
// on Wikidata) fall back to the shield placeholder.

export type PlayerPhoto = {
  file: string;
  author: string;
  licence: string;
  licenceUrl: string;
  source: string;
};

export const PLAYER_PHOTOS: Record<string, PlayerPhoto> = {
  'A. Cole': {
    file: 'a-cole.jpg',
    author: 'Stanislav Vedmid',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:ACole.JPG',
  },
  'Abidal': {
    file: 'abidal.jpg',
    author: 'Mutari 16:30, 5 March 2008 (UTC)',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:%C3%89ric_Abidal_-_001.jpg',
  },
  'Agüero': {
    file: 'aguero.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ag%C3%BCero_in_2018.jpg',
  },
  'Alaba': {
    file: 'alaba.jpg',
    author: 'Granada',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:20180610_FIFA_Friendly_Match_Austria_vs._Brazil_David_Alaba_850_1632.jpg',
  },
  'Alba': {
    file: 'alba.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Russia-Spain_2017_(11).jpg',
  },
  'Alex': {
    file: 'alex.jpg',
    author: 'TomekBlaszczyk',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Alex_Rodrigo_Dias_da_Costa.jpg',
  },
  'Alexander-Arnold': {
    file: 'alexander-arnold.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Trent_Alexander-Arnold_2018_(cropped).jpg',
  },
  'Alisson': {
    file: 'alisson.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Alisson_Becker_Brazil_V_Morocco_13_June_2026-117_(cropped).jpg',
  },
  'Alves': {
    file: 'alves.jpg',
    author: 'Palácio do Planalto from Brasilia, Brasil',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:07_07_2019_Final_da_Copa_Am%C3%A9rica_2019_(48226649586)_(cropped).jpg',
  },
  'Ambrosini': {
    file: 'ambrosini.jpg',
    author: 'Io',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Massimo_Ambrosini_in_2008.jpg',
  },
  'Amor': {
    file: 'amor.jpg',
    author: 'Jordiferrer',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Guillermo-Amor-Barcelona-1992.jpg',
  },
  'Bakero': {
    file: 'bakero.jpg',
    author: 'Roger Goraczniak',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jos%C3%A9_Mari_Bakero.jpg',
  },
  'Bale': {
    file: 'bale.jpg',
    author: 'Дмитрий Журавель',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gareth_Bale_2015_(1).jpg',
  },
  'Ballack': {
    file: 'ballack.jpg',
    author: 'Bernhard Holub',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Michael_Ballack_2022_BHO-0832.jpg',
  },
  'Beckham': {
    file: 'beckham.jpg',
    author: 'The Democratic Alliance',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:David_Beckham_2009.jpg',
  },
  'Beguiristain': {
    file: 'beguiristain.jpg',
    author: 'Biser Todorov',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Txiki_Begiristain_2016_(cropped).jpg',
  },
  'Benzema': {
    file: 'benzema.jpg',
    author: 'Zack',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Karim_Benzema_Pick.jpg',
  },
  'Bergkamp': {
    file: 'bergkamp.jpg',
    author: 'Kieran Clarke',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dennis_Bergkamp_2014_(cropped).jpg',
  },
  'Boateng': {
    file: 'boateng.jpg',
    author: 'Rufus46',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jerome_Boateng_Training_2019-04-10_FC_Bayern_Muenchen-2_(cropped).jpg',
  },
  'Brown': {
    file: 'brown.jpg',
    author: 'Andrea Sartorati',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Brown_Manchester_-_Old_Trafford_-_Manchester_United_vs_Crawley_Town.jpg',
  },
  'Busquets': {
    file: 'busquets.jpg',
    author: 'Анна Нэсси',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sergio_Busquets_2018_(cropped).jpg',
  },
  'C. Alberto': {
    file: 'c-alberto.jpg',
    author: 'Shaoqiang at German Wikipedia jugo junto al colombiano camilo arce leon (Original text: \'camilo arce)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Calberto.jpg',
  },
  'Cambiasso': {
    file: 'cambiasso.jpg',
    author: 'Ludovic Péron',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Esteban_Cambiasso_-_2011.jpg',
  },
  'Campbell': {
    file: 'campbell.jpg',
    author: 'Stefan Schäfer, Lich',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sol_Campbell2014.jpg',
  },
  'Carrick': {
    file: 'carrick.jpg',
    author: 'Timmy96',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Michael_Carrick_12042025_(5)_(cropped).jpg',
  },
  'Carvajal': {
    file: 'carvajal.jpg',
    author: 'Rolandhino1',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Dani_Carvajal_10_(cropped).jpg',
  },
  'Carvalho': {
    file: 'carvalho.jpg',
    author: 'Jan S0L0',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Carvalho_in_2010-11_Real_Madrid.jpg',
  },
  'Casemiro': {
    file: 'casemiro.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Casemiro_Brazil_V_Morocco_13_June_2026-76_(cropped).jpg',
  },
  'Casillas': {
    file: 'casillas.jpg',
    author: 'Зайцев Антон',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Iker_Casillas_2.jpg',
  },
  'Čech': {
    file: 'cech.jpg',
    author: 'Warrenfish',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Petr_%C4%8Cech_Chelsea_2013.jpg',
  },
  'Chivu': {
    file: 'chivu.jpg',
    author: 'Майоров Владимир',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cristian_Chivu_2011.jpg',
  },
  'Cleverley': {
    file: 'cleverley.jpg',
    author: 'Tommy Low from Singapore, Singapore',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tom_Cleverley_2015.jpg',
  },
  'Coentrão': {
    file: 'coentrao.jpg',
    author: 'Майоров Владимир',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:4F%C3%A1bio_Coentr%C3%A3o.jpg',
  },
  'Cole': {
    file: 'cole.jpg',
    author: 'Norio NAKAYAMA from saitama, japan',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Aeroflot_Manchester_United_Trophy_Tour_in_Tokyo_(13047502155).jpg',
  },
  'Costinha': {
    file: 'costinha.jpg',
    author: 'Christophe95',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Costinha_(footballer_born_1974).jpg',
  },
  'D. Silva': {
    file: 'd-silva.jpg',
    author: 'Дмитрий Неймырок',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:David_Silva_Euro_2012_vs_France_01.jpg',
  },
  'De Bruyne': {
    file: 'de-bruyne.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_(cropped).jpg',
  },
  'De Gea': {
    file: 'de-gea.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:David_de_Gea_2017.jpg',
  },
  'Deco': {
    file: 'deco.jpg',
    author: 'John Dobson',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Chelsea_Deco.jpg',
  },
  'Delph': {
    file: 'delph.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fabian_Delph_2018-06-28_3.jpg',
  },
  'Dembélé': {
    file: 'dembele.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ousmane_Dembele_France_v_Senegal_16_June_2026-341_(cropped).jpg',
  },
  'Derlei': {
    file: 'derlei.jpg',
    author: 'Alexander Oganezov aka Sasho68',
    licence: 'Public domain',
    licenceUrl: '',
    source: 'https://commons.wikimedia.org/wiki/File:Derlei.jpg',
  },
  'Di María': {
    file: 'di-maria.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:NIG-ARG_(5).jpg',
  },
  'Dida': {
    file: 'dida.jpg',
    author: 'NullReason',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dida-wikipedia_(cropped_2).png',
  },
  'Donnarumma': {
    file: 'donnarumma.jpg',
    author: 'Original: MichaelEmilio / Derivative work: Danyele',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Norway_Italy_-_June_2025_B_33_-_Gianluigi_Donnarumma_(close-up).jpg',
  },
  'Doué': {
    file: 'doue.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Desire_Doue_France_v_Norway_26_June_26-032.jpg',
  },
  'Drogba': {
    file: 'drogba.jpg',
    author: 'Y.Leclercq©',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Didier_Drogba_(2019)_(cropped).jpg',
  },
  'Duff': {
    file: 'duff.jpg',
    author: 'Mikhail Slain',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:DDuff.JPG',
  },
  'Ederson': {
    file: 'ederson.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ederson_(cropped).png',
  },
  'Eto\'o': {
    file: 'eto-o.jpg',
    author: 'BACHELOR45',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sammuel_Eto%27o_Fils_02.jpg',
  },
  'Evra': {
    file: 'evra.jpg',
    author: 'Web Summit',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Patrice_Evra_(52472689279)_(cropped).jpg',
  },
  'Fabinho': {
    file: 'fabinho.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fabinho_Brazil_V_Morocco_13_June_2026-70.jpg',
  },
  'Ferdinand': {
    file: 'ferdinand.jpg',
    author: 'Web Summit',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Web_Summit_2015_-_Dublin,_Ireland_-_22183056474_(cropped).jpg',
  },
  'Fernandinho': {
    file: 'fernandinho.jpg',
    author: 'Ailura',
    licence: 'CC BY-SA 3.0 at',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/at/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:20141118_AUTBRA_5080.jpg',
  },
  'Ferrer': {
    file: 'ferrer.jpg',
    author: 'Jordiferrer',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Albert-Ferrer-Barcelona-1992.jpg',
  },
  'Firmino': {
    file: 'firmino.jpg',
    author: 'Granada',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Roberto_Firmino_850_1557.jpg',
  },
  'G. Neville': {
    file: 'g-neville.jpg',
    author: 'University of Salford Press Office',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gary_Neville_2014_(cropped).jpg',
  },
  'Gallas': {
    file: 'gallas.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:William_Gallas_2018_(2).jpg',
  },
  'Gattuso': {
    file: 'gattuso.jpg',
    author: 'Рыбакова Елена',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Gennaro_Gattuso_2008.jpg',
  },
  'Giggs': {
    file: 'giggs.jpg',
    author: 'James Adams',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ryan_Giggs_in_2008.jpg',
  },
  'Gilberto': {
    file: 'gilberto.jpg',
    author: 'Web Summit',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:2021_-_Press_conferences_SM7_0168_(51649502936)_(cropped).jpg',
  },
  'Guardiola': {
    file: 'guardiola.jpg',
    author: 'Steffen Prößdorf',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Josep_Guardiola_2023-10-04_Fu%C3%9Fball,_M%C3%A4nner,_UEFA_Champions_League,_RB_Leipzig_-_Manchester_City_FC_1DX_2797_(cropped).jpg',
  },
  'Hakimi': {
    file: 'hakimi.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg',
  },
  'Hargreaves': {
    file: 'hargreaves.jpg',
    author: 'Gordon Flood from Trim, Ireland',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:O_Hargreaves.jpg',
  },
  'Henderson': {
    file: 'henderson.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jordan_Henderson_England_v_Ghana_23_June_2026-029_(cropped).jpg',
  },
  'Henry': {
    file: 'henry.jpg',
    author: 'Web Summit',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Thierry_Henry_(51649035951)_(cropped).jpg',
  },
  'Iniesta': {
    file: 'iniesta.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Andr%C3%A9s_Iniesta_Argentina_v_Spain_19_July_2026-034_(cropped).jpg',
  },
  'Inzaghi': {
    file: 'inzaghi.jpg',
    author: 'Delfort',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Filippo_Inzaghi_2011.jpg',
  },
  'Irwin': {
    file: 'irwin.jpg',
    author: 'Kjetil Ree',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Denis_Irwin_(2017-07-29_img06)_(cropped).jpg',
  },
  'Isco': {
    file: 'isco.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Liver-RM_(5)_(cropped_2).jpg',
  },
  'Ivanović': {
    file: 'ivanovic.jpg',
    author: 'Вячеслав Евдокимов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Branislav_Ivanovi%C4%87_2020.jpg',
  },
  'Johnsen': {
    file: 'johnsen.jpg',
    author: 'Kjetil Ree',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ronny_Johnsen_(2017-07-29_img02).jpg',
  },
  'Júlio César': {
    file: 'julio-cesar.jpg',
    author: 'Майоров Владимир',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:J%C3%BAlio_C%C3%A9sar_FC_Internazionale.jpg',
  },
  'Kagawa': {
    file: 'kagawa.jpg',
    author: 'Кагава Синдзи',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Shinji_Kagawa_2018_(cropped).jpg',
  },
  'Kaká': {
    file: 'kaka.jpg',
    author: 'José Cruz/ABr (cropped by tales.ebner)',
    licence: 'CC BY 3.0 br',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0/br/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Ricardo_Izecson_dos_Santos_Leite_(Kak%C3%A1)_01.jpg',
  },
  'Keane': {
    file: 'keane.jpg',
    author: 'Irish Defence Forces from Ireland',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Roy_keane_2014.jpg',
  },
  'Koeman': {
    file: 'koeman.jpg',
    author: 'Richard Mulder',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ronald_Koeman_(2014)_(cropped).jpg',
  },
  'Kroos': {
    file: 'kroos.jpg',
    author: 'https://www.youtube.com/@realmadrid',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Toni_Kroos_Real_Madrid_2021.jpg',
  },
  'Kvaratskhelia': {
    file: 'kvaratskhelia.jpg',
    author: 'გიორგი კეკელიძის პირადი არქივი',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Khvicha_Kvaratskhelia_cropped.jpg',
  },
  'Lahm': {
    file: 'lahm.jpg',
    author: 'Elena Ternovaja',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Philipp_Lahm_auf_der_Berlinale_2024,_Ausschnitt.jpg',
  },
  'Lampard': {
    file: 'lampard.jpg',
    author: 'Mehdi Bolourian',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Frank_Lampard_2019.jpg',
  },
  'Lauren': {
    file: 'lauren.jpg',
    author: 'Chensiyuan',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:1_Laureano_Bisan_Etam%C3%A9-Mayer.jpg',
  },
  'Lehmann': {
    file: 'lehmann.jpg',
    author: 'Siebbi',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jens_Lehmann_(Berlin_Film_Festival_2011).jpg',
  },
  'Lewandowski': {
    file: 'lewandowski.jpg',
    author: 'Светлана Бекетова',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Robert_Lewandowski_2018,_JAP-POL_(cropped).jpg',
  },
  'Ljungberg': {
    file: 'ljungberg.jpg',
    author: 'Ricardo Alvarez',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fredrik_Ljungberg_2006.jpg',
  },
  'Lúcio': {
    file: 'lucio.jpg',
    author: 'Palácio do Planalto from Brasilia, Brasil',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Lucio_2019_(cropped).jpg',
  },
  'Maicon': {
    file: 'maicon.jpg',
    author: 'Steindy (talk) 23:39, 28 November 2009 (UTC)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Maicon_Douglas_Sisenando_-_Inter_Mailand_(2).jpg',
  },
  'Makélélé': {
    file: 'makelele.jpg',
    author: 'Web Summit Qatar',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Claude_Mak%C3%A9l%C3%A9l%C3%A9_(53557564951)_(cropped).jpg',
  },
  'Maldini': {
    file: 'maldini.jpg',
    author: 'Foad Ashtari',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Paolo_Maldini_press_conference_in_Tehran_(cropped).jpg',
  },
  'Malouda': {
    file: 'malouda.jpg',
    author: 'Stanislav Vedmid',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Malouda2012.JPG',
  },
  'Mané': {
    file: 'mane.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg',
  },
  'Maniche': {
    file: 'maniche.jpg',
    author: 'José Goulão from Lisbon, Portugal',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Portugal_2-3_Denmark,_Maniche.jpg',
  },
  'Marcelo': {
    file: 'marcelo.jpg',
    author: 'Granada',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Marcelo_850_1622.jpg',
  },
  'Marquinhos': {
    file: 'marquinhos.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Marquinhos_Brazil_V_Morocco_13_June_2026-153_(cropped).jpg',
  },
  'Martínez': {
    file: 'martinez.jpg',
    author: 'Rufus46',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Javi_Martinez_Training_2017-03_FC_Bayern_Muenchen-1_(cropped).jpg',
  },
  'Mascherano': {
    file: 'mascherano.jpg',
    author: 'Not credited',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Mascherano_casagob.jpg',
  },
  'Matip': {
    file: 'matip.jpg',
    author: 'Steffen Prößdorf',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:2022-07-21_Fu%C3%9Fball,_M%C3%A4nner,Freundschaftsspiel,_RB_Leipzig_-_FC_Liverpool_1DX_2092_by_Stepro_(cropped).jpg',
  },
  'Mendes': {
    file: 'mendes.jpg',
    author: 'Екатерина Лаут',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Pedro_Mendes_2018.jpg',
  },
  'Messi': {
    file: 'messi.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg',
  },
  'Mikel': {
    file: 'mikel.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:John_Obi_Mikel_2018.jpg',
  },
  'Milito': {
    file: 'milito.jpg',
    author: 'Steindy (talk) 13:14, 28 November 2009 (UTC)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Diego_Milito_-_Inter_Mailand_(3).jpg',
  },
  'Modrić': {
    file: 'modric.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Luka_Modric_Croatia_v_Portugal_2_July_2026-055.jpg',
  },
  'Müller': {
    file: 'muller.jpg',
    author: 'Werner100359',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Thomas_M%C3%BCller_2022_(cropped).jpg',
  },
  'Nadal': {
    file: 'nadal.jpg',
    author: 'Biser Todorov',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Miguel_Angel_Nadal_in_2016.jpg',
  },
  'Navas': {
    file: 'navas.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Keylor_Navas_2018_(cropped).jpg',
  },
  'Nesta': {
    file: 'nesta.jpg',
    author: 'Joerudi',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Alessandro_Nesta_as_Miami_FC_Manager.jpg',
  },
  'Neuer': {
    file: 'neuer.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Manuel_Neuer_Ecuador_v_Germany_25_June_2026-148.jpg',
  },
  'Neves': {
    file: 'neves.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jo%C3%A3o_Neves_USMNT_v_Portugal_Mar_31_2026-18_(cropped).jpg',
  },
  'Neymar': {
    file: 'neymar.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg',
  },
  'Nuno Mendes': {
    file: 'nuno-mendes.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Nuno_Mendes_Croatia_v_Portugal_2_July_2026-135_(cropped).jpg',
  },
  'Oddo': {
    file: 'oddo.jpg',
    author: 'Mech867',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Oddo_Perugia.jpg',
  },
  'Otamendi': {
    file: 'otamendi.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Nicolas_Otamendi_Argentina_v_Egypt_7_July_2026-030.jpg',
  },
  'P. Ferreira': {
    file: 'p-ferreira.jpg',
    author: '@cfcunofficial (Chelsea Debs) London',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Paulo_Ferreira_2017.jpg',
  },
  'Pacho': {
    file: 'pacho.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Willian_Pacho_Ecuador_v_Germany_25_June_2026-228.jpg',
  },
  'Pandev': {
    file: 'pandev.jpg',
    author: 'Новикова Юлия',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Goran_Pandev.JPG',
  },
  'Pedro': {
    file: 'pedro.jpg',
    author: 'Clément Bucco-Lechat',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Bar%C3%A7a_-_Napoli_-_20140806_-_Pedro_Rodriguez_(cropped).jpg',
  },
  'Pepe': {
    file: 'pepe.jpg',
    author: 'Дмитрий Садовников',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Russia-Portugal_CC2017_(11_(cropped).jpg',
  },
  'Piqué': {
    file: 'pique.jpg',
    author: 'Vinod Divakaran',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:GerardPique.jpg',
  },
  'Pires': {
    file: 'pires.jpg',
    author: 'Zack',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Robert_Pir%C3%A8s.jpg',
  },
  'Pirlo': {
    file: 'pirlo.jpg',
    author: 'Clément Bucco-Lechat',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:20150616_-_Portugal_-_Italie_-_Gen%C3%A8ve_-_Andrea_Pirlo_(cropped).jpg',
  },
  'Puyol': {
    file: 'puyol.jpg',
    author: 'Darz Mol',
    licence: 'CC BY-SA 2.5 es',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.5/es/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Carles_Puyol_18abr2007.jpg',
  },
  'Rafael': {
    file: 'rafael.jpg',
    author: 'Andrea Sartorati',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Rafael_Man_Utd_2011.jpg',
  },
  'Rakitić': {
    file: 'rakitic.jpg',
    author: 'Дмитрий Пукалик',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Ivan_Rakiti%C4%87_2020_(cropped).jpg',
  },
  'Ramos': {
    file: 'ramos.jpg',
    author: 'Real Madrid',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sergio_Ramos_Interview_2021_(cropped).jpg',
  },
  'Ribéry': {
    file: 'ribery.jpg',
    author: 'Sven Mandel',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Franck_Ribery_2019_(cropped).jpg',
  },
  'Robben': {
    file: 'robben.jpg',
    author: 'Дмитрий Садовников',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Arjen_Robben_2013.jpg',
  },
  'Robertson': {
    file: 'robertson.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Andy_Robertson_Scotland_v_Bolivia_6_June_2026-43.jpg',
  },
  'Romário': {
    file: 'romario.jpg',
    author: 'Agência Senado from Brasilia, Brazil',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Senadores_da_57%C2%AA_Legislatura_(52689451805).jpg',
  },
  'Ronaldo': {
    file: 'ronaldo.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_(cropped).jpg',
  },
  'Rooney': {
    file: 'rooney.jpg',
    author: 'Дмитрий Голубович',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Wayne-Rooney-2015-10-21.jpg',
  },
  'Ruiz': {
    file: 'ruiz.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Fabian_Ruiz_Argentina_v_Spain_19_July_2026-315.jpg',
  },
  'Salah': {
    file: 'salah.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Mohamed_Salah_Argentina_v_Egypt_7_July_2026-163_(cropped).jpg',
  },
  'Samuel': {
    file: 'samuel.jpg',
    author: 'Steindy (talk) 17:05, 29 November 2009 (UTC)',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Walter_Samuel_-_Inter_Mailand_(1).jpg',
  },
  'Sané': {
    file: 'sane.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Leroy_Sane_Ecuador_v_Germany_25_June_2026-004.jpg',
  },
  'Schmeichel': {
    file: 'schmeichel.jpg',
    author: 'Carlsberg',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Peter_Schmeichel_2012-01-25_001.jpg',
  },
  'Scholes': {
    file: 'scholes.jpg',
    author: 'James Adams',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:P_Scholes.jpg',
  },
  'Seedorf': {
    file: 'seedorf.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Clarence_Seedorf_2021.jpg',
  },
  'Sergi': {
    file: 'sergi.jpg',
    author: 'Dynamomania.com',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:%D0%A1%D0%B5%D1%80%D1%85%D1%96_%D0%91%D0%B0%D1%80%D1%85%D1%83%D0%B0%D0%BD_(cropped).jpg',
  },
  'Sneijder': {
    file: 'sneijder.jpg',
    author: 'Dmitry Neimyrok',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Wesley2012.JPG',
  },
  'Stam': {
    file: 'stam.jpg',
    author: 'Original: Flovries Derivative work: PeeJay2K3',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Jaap_Stam_met_fan_cropped.jpg',
  },
  'Sterling': {
    file: 'sterling.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Raheem_Sterling_2018.jpg',
  },
  'Stoichkov': {
    file: 'stoichkov.jpg',
    author: 'Biso',
    licence: 'CC BY 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Hristo_stoichkov-2010.jpg',
  },
  'Stones': {
    file: 'stones.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:John_Stones_England_v_Ghana_23_June_2026-038.jpg',
  },
  'Suárez': {
    file: 'suarez.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Luis_Su%C3%A1rez_NE_Revolution_Inter_Miami_7.9.25-053_(cropped).jpg',
  },
  'Ter Stegen': {
    file: 'ter-stegen.jpg',
    author: 'Government of Catalonia',
    licence: 'CC0',
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Marc-Andre_Ter_Stegen_ACCI_FCBARCELONA_Turisme_Catalunya_gira_pretemporada_CATPRESS.jpg',
  },
  'Terry': {
    file: 'terry.jpg',
    author: 'ChristopherJClarke',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:John_Terry_at_pro-am_Wentworth_golf_course_September_2023_(cropped).jpg',
  },
  'Tévez': {
    file: 'tevez.jpg',
    author: 'Egghead06',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Carlos_Tevez_with_Argentina_November_2014_(cropped).jpg',
  },
  'Thiago': {
    file: 'thiago.jpg',
    author: 'Rolandhino1',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Thiago_Alcantara_13_(cropped).jpg',
  },
  'Tiago': {
    file: 'tiago.jpg',
    author: 'Carlos Delgado',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Tiago_Mendes_-_01.jpg',
  },
  'Touré': {
    file: 'toure.jpg',
    author: 'Ailura',
    licence: 'CC BY-SA 3.0 at',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/at/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Kolo_Toure_8932.JPG',
  },
  'Valdés': {
    file: 'valdes.jpg',
    author: 'Дмитрий Неймырок',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:V%C3%ADctor_Vald%C3%A9s_before_Euro_2012_vs_France_(cropped).jpg',
  },
  'Valencia': {
    file: 'valencia.jpg',
    author: 'Julia Novikova for Soccer.ru',
    licence: 'CC BY-SA 1.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/1.0',
    source: 'https://commons.wikimedia.org/wiki/File:Antonio_Valencia_cropped.jpg',
  },
  'Van der Sar': {
    file: 'van-der-sar.jpg',
    author: 'Paul Blank',
    licence: 'CC BY 2.5',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.5',
    source: 'https://commons.wikimedia.org/wiki/File:Edwin_van_der_Sar_side.jpg',
  },
  'Van Dijk': {
    file: 'van-dijk.jpg',
    author: 'Ailura',
    licence: 'CC BY-SA 3.0 at',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/at/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:20160604_AUT_NED_8876_(cropped).jpg',
  },
  'Van Persie': {
    file: 'van-persie.jpg',
    author: 'Елена Рыбакова',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Loco-Fener_(10).jpg',
  },
  'Varane': {
    file: 'varane.jpg',
    author: 'Антон Зайцев',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Liver-RM_(8)_(Varane).jpg',
  },
  'Vidić': {
    file: 'vidic.jpg',
    author: 'Austin Osuide',
    licence: 'CC BY 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Nemanja_Vidi%C4%87.jpg',
  },
  'Vieira': {
    file: 'vieira.jpg',
    author: 'Simon Heseltine',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Patrick_Vieira_NYCFC.JPG',
  },
  'Villa': {
    file: 'villa.jpg',
    author: 'Tânia Rêgo/ABr',
    licence: 'CC BY 3.0 br',
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0/br/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:Spain-Tahiti,_Confederations_Cup_2013_(02)_(Villa_crop).jpg',
  },
  'Vitinha': {
    file: 'vitinha.jpg',
    author: 'Bryan Berlin',
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Vitinha_USMNT_v_Portugal_Mar_31_2026-50_(cropped).jpg',
  },
  'Vítor Baía': {
    file: 'vitor-baia.jpg',
    author: 'Christophe95',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:V%C3%ADtor_Ba%C3%ADa.JPG',
  },
  'Walker': {
    file: 'walker.jpg',
    author: 'Кирилл Венедиктов',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kyle_Walker.jpg',
  },
  'Wijnaldum': {
    file: 'wijnaldum.jpg',
    author: 'Ailura',
    licence: 'CC BY-SA 3.0 at',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/at/deed.en',
    source: 'https://commons.wikimedia.org/wiki/File:20160604_AUT_NED_8839.jpg',
  },
  'Xabi Alonso': {
    file: 'xabi-alonso.jpg',
    author: 'DONOSTIA KULTURA',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Los_Caminos_del_f%C3%BAtbol._Xabi_Alonso_(39666778464)_(cropped).jpg',
  },
  'Xavi': {
    file: 'xavi.jpg',
    author: 'Mehdi Zare',
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Xavi_13981129001173637176666027076571.jpg',
  },
  'Yorke': {
    file: 'yorke.jpg',
    author: 'Deepti Soni',
    licence: 'CC BY-SA 2.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Dwight_Yorke_in_Chennai.jpg',
  },
  'Zanetti': {
    file: 'zanetti.jpg',
    author: 'Давиденко Валерий',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Javier_Adelmar_Zanetti.jpg',
  },
  'Zubizarreta': {
    file: 'zubizarreta.jpg',
    author: 'Pepito',
    licence: 'CC BY-SA 3.0',
    licenceUrl: 'http://creativecommons.org/licenses/by-sa/3.0/',
    source: 'https://commons.wikimedia.org/wiki/File:Andoni_Zubizarreta.jpg',
  },
};

export const playerPhotoUrl = (file: string) => `${import.meta.env.BASE_URL}players/${file}`;
